/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddClubDialog: typeof import('./src/components/clubs/AddClubDialog.vue')['default']
    AddMatchDialog: typeof import('./src/components/tournaments/AddMatchDialog.vue')['default']
    AddPlayerDialog: typeof import('./src/components/players/AddPlayerDialog.vue')['default']
    AddTournamentDialog: typeof import('./src/components/tournaments/AddTournamentDialog.vue')['default']
    AppNavbar: typeof import('./src/components/AppNavbar.vue')['default']
    DeleteButtonWithAlert: typeof import('./src/components/DeleteButtonWithAlert.vue')['default']
    ErrorSnackbar: typeof import('./src/components/ErrorSnackbar.vue')['default']
    MatchesSearch: typeof import('./src/components/tournaments/MatchesSearch.vue')['default']
    ModifyClubForm: typeof import('./src/components/clubs/ModifyClubForm.vue')['default']
    ModifyPlayerForm: typeof import('./src/components/players/ModifyPlayerForm.vue')['default']
    ModifyTournamentForm: typeof import('./src/components/tournaments/ModifyTournamentForm.vue')['default']
    PlayerGamesChart: typeof import('./src/components/players/PlayerGamesChart.vue')['default']
    PlayersSearchTable: typeof import('./src/components/clubs/PlayersSearchTable.vue')['default']
    PlayerStatistics: typeof import('./src/components/players/PlayerStatistics.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TournamentDisplay: typeof import('./src/components/tournaments/TournamentDisplay.vue')['default']
  }
}
