/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/klubid/': RouteRecordInfo<'/klubid/', '/klubid', Record<never, never>, Record<never, never>>,
    '/klubid/[id]': RouteRecordInfo<'/klubid/[id]', '/klubid/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/mangijad/': RouteRecordInfo<'/mangijad/', '/mangijad', Record<never, never>, Record<never, never>>,
    '/mangijad/[id]': RouteRecordInfo<'/mangijad/[id]', '/mangijad/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/turniirid/': RouteRecordInfo<'/turniirid/', '/turniirid', Record<never, never>, Record<never, never>>,
    '/turniirid/[id]': RouteRecordInfo<'/turniirid/[id]', '/turniirid/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
